<?php

namespace AppBundle\Entity;

use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    /**
     * Find categories ordered by name
     *
     * @return mixed
     */
    public function findAllOrderedAscDql()
    {
        $dql = 'SELECT c FROM AppBundle:Category c ORDER BY c.name ASC';
        $query = $this->getEntityManager()->createQuery($dql);

        return $query->execute();
    }

    /**
     * Find categories ordered by name
     *
     * @return mixed
     */
    public function findAllOrdered()
    {
        $qb = $this->createQueryBuilder('c');

        return $this->addFortuneCookieJoinAndSelect($qb)
            ->addOrderBy('c.name', 'DESC')
            ->getQuery()
            ->execute();
    }

    /**
     * Search categories by name, icon or fortune
     *
     * @param string $term
     * @return mixed
     */
    public function search($term)
    {
        $qb = $this->createQueryBuilder('c')
            ->andWhere('c.name LIKE :term
            OR c.iconKey LIKE :term
            OR fc.fortune LIKE :term');

        return $this->addFortuneCookieJoinAndSelect($qb)
            ->setParameter('term', '%' . $term . '%')
            ->addOrderBy('c.name', 'DESC')
            ->getQuery()
            ->execute();
    }

    /**
     * Find categories inner join fortunes
     *
     * @param integer $id
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findWithFortunesJoin($id)
    {
        $qb = $this->createQueryBuilder('c');

        return $this->addFortuneCookieJoinAndSelect($qb)
            ->andWhere('c.id = :id')
            ->setParameter(':id', $id)
            ->getQuery()
            ->getOneOrNullResult();
    }

    /**
     * Avoid DRY code, fortune cookie join and select
     *
     * @param QueryBuilder $qb
     * @return QueryBuilder
     */
    private function addFortuneCookieJoinAndSelect(QueryBuilder $qb)
    {
        return $qb
            ->leftJoin('c.fortuneCookies', 'fc')
            ->addSelect('fc');
    }
}
