<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FortuneCookieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FortuneCookieRepository extends EntityRepository
{
    public function findTotalPrinted(Category $category)
    {
        return $this->createQueryBuilder('fc')
            ->andWhere('fc.category = :category')
            ->setParameter('category', $category)
            ->select('SUM(fc.numberPrinted)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    public function findTotalAverageNameData(Category $category)
    {
        return $this->createQueryBuilder('fc')
            ->innerJoin('fc.category', 'c')
            ->andWhere('fc.category = :category')
            ->setParameter('category', $category)
            ->select('SUM(fc.numberPrinted) total, AVG(fc.numberPrinted) average, c.name')
            ->getQuery()
            ->getOneOrNullResult();
    }

    public function plainSqlQuery(Category $category)
    {
        $conn = $this->getEntityManager()->getConnection();

        $sql = 'SELECT
                    SUM(fc.numberPrinted) total, AVG(fc.numberPrinted) average, c.name
                  FROM fortune_cookie fc
                  INNER JOIN category c ON c.id = fc.category_id
                  WHERE category_id = :category
                  ';
        $stmt = $conn->prepare($sql);
        $stmt->execute(
            ['category' => $category->getId()]
        );

        return $stmt->fetch();
    }
}
